# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name = "Test"
  agent = "Bhimbai-12345"

steps:
- task: UiPathTest@6
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'UiPath_Cloud_Connection_Test'
    testProjectPath: 'project.json'
    folderName: 'AzureCICDTesting'
    testReportDestination: 'result.json'
    traceLevel: 'Information'
    